version: "2"
run:
  concurrency: 2
linters:
  default: none
  enable:
    - gosec
    - govet
    - ineffassign
    - revive
    - unconvert
    - unused
exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - docs
      - baseimages
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - docs
      - baseimages
      - third_party$
      - builtin$
      - examples$
