trigger:
- master

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- script: |
    go version
    go env
    go build ./cmd/acr/... 
  displayName: 'Build'

- script: |
    go test ./... 
  displayName: 'Test'