trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    set -e
    GOOS=linux scripts/setup/dev_setup
    echo '##vso[task.prependpath]$(go env GOPATH)/bin'
  displayName: 'Setup'
- script: |
    set -e
    COOS=linux make lint build binaries test
  displayName: 'Build'