package acrapi

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"

	"github.com/Azure/acr-cli/acr"
	"github.com/Azure/go-autorest/autorest"
)

// BaseClientAPI contains the set of methods on the BaseClient type.
type BaseClientAPI interface {
	CancelBlobUpload(ctx context.Context, name string, UUID string) (result autorest.Response, err error)
	CheckBlobExistence(ctx context.Context, name string, digest string) (result autorest.Response, err error)
	CreateManifest(ctx context.Context, name string, reference string, payload acr.Manifest) (result acr.SetObject, err error)
	DeleteAcrManifestMetadata(ctx context.Context, name string, reference string, metadata string) (result autorest.Response, err error)
	DeleteAcrRepository(ctx context.Context, name string) (result acr.DeletedRepository, err error)
	DeleteAcrRepositoryMetadata(ctx context.Context, name string, metadata string) (result autorest.Response, err error)
	DeleteAcrTag(ctx context.Context, name string, reference string) (result autorest.Response, err error)
	DeleteAcrTagMetadata(ctx context.Context, name string, reference string, metadata string) (result autorest.Response, err error)
	DeleteManifest(ctx context.Context, name string, reference string) (result autorest.Response, err error)
	EndBlobUpload(ctx context.Context, digest string, name string, UUID string) (result autorest.Response, err error)
	GetAcrAccessToken(ctx context.Context, service string, scope string, refreshToken string) (result acr.AccessToken, err error)
	GetAcrAccessTokenFromLogin(ctx context.Context, service string, scope string) (result acr.AccessToken, err error)
	GetAcrManifestAttributes(ctx context.Context, name string, reference string) (result acr.ManifestAttributes, err error)
	GetAcrManifestMetadata(ctx context.Context, name string, reference string, metadata string) (result acr.SetObject, err error)
	GetAcrManifests(ctx context.Context, name string, last string, n *int32, orderby string) (result acr.Manifests, err error)
	GetAcrRefreshTokenFromExchange(ctx context.Context, grantType string, service string, tenant string, refreshToken string, accessToken string) (result acr.RefreshToken, err error)
	GetAcrRepositories(ctx context.Context, last string, n *int32) (result acr.Repositories, err error)
	GetAcrRepositoryAttributes(ctx context.Context, name string) (result acr.RepositoryAttributes, err error)
	GetAcrRepositoryMetadata(ctx context.Context, name string, metadata string) (result acr.SetObject, err error)
	GetAcrTagAttributes(ctx context.Context, name string, reference string) (result acr.TagAttributesType, err error)
	GetAcrTagMetadata(ctx context.Context, name string, reference string, metadata string) (result acr.SetObject, err error)
	GetAcrTags(ctx context.Context, name string, last string, n *int32, orderby string, digest string) (result acr.RepositoryTagsType, err error)
	GetBlob(ctx context.Context, name string, digest string) (result acr.String, err error)
	GetBlobUploadStatus(ctx context.Context, name string, UUID string) (result autorest.Response, err error)
	GetDockerRegistryV2Support(ctx context.Context) (result autorest.Response, err error)
	GetManifest(ctx context.Context, name string, reference string, accept string) (result acr.Manifest, err error)
	GetRepositories(ctx context.Context, last string, n *int32) (result acr.Repositories, err error)
	GetTagList(ctx context.Context, name string) (result acr.RepositoryTags, err error)
	ListManifestMetadata(ctx context.Context, name string, reference string) (result acr.ManifestMetadataList, err error)
	ListRepositoryMetadata(ctx context.Context, name string) (result acr.RepositoryMetadata, err error)
	ListTagMetadata(ctx context.Context, name string, reference string) (result acr.TagMetadataList, err error)
	StartBlobUpload(ctx context.Context, name string, digest string, from string, mount string) (result autorest.Response, err error)
	UpdateAcrManifestAttributes(ctx context.Context, name string, reference string, value *acr.ChangeableAttributes) (result autorest.Response, err error)
	UpdateAcrManifestMetadata(ctx context.Context, name string, reference string, metadata string, value *interface{}) (result autorest.Response, err error)
	UpdateAcrRepositoryAttributes(ctx context.Context, name string, value *acr.ChangeableAttributes) (result autorest.Response, err error)
	UpdateAcrRepositoryMetadata(ctx context.Context, name string, metadata string, value *interface{}) (result autorest.Response, err error)
	UpdateAcrTagAttributes(ctx context.Context, name string, reference string, value *acr.ChangeableAttributes) (result autorest.Response, err error)
	UpdateAcrTagMetadata(ctx context.Context, name string, reference string, metadata string, value *interface{}) (result autorest.Response, err error)
	UploadBlobContent(ctx context.Context, name string, UUID string) (result autorest.Response, err error)
}

var _ BaseClientAPI = (*acr.BaseClient)(nil)
